---
title: "final_code Writeup"
output: word_document
---

```{r libraries, include=FALSE ,warning=FALSE ,message=FALSE}
#########################################################
## Libraries
#########################################################
library(ggthemes)
library(scales)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(rstudioapi)
library(naniar)
library(lubridate)
library(ggcorrplot)
library(leaps)
library(glmnet)
# library(caret)
library(magrittr)
library(MASS)
# library(randomForest)
# library(gbm)
library(tidyverse)

## Turn off scientific notation
options(scipen = 999)


```

## Data Read

```{r data_read, include=FALSE}
#########################################################
## Data Read
#########################################################
## Set the working directory to path of saved R script
# setwd(getActiveDocumentContext()$path %>% 
#         str_remove_all(pattern = "final_code\\.R"))

## Reading in all the files
raw_claims_data <- read_csv("Claim_Fraud_data__Claims.csv")
raw_assessment_data <- read_csv("Claim_Fraud_data_Assessment.csv")
raw_driver_data <- read_csv("Claim_Fraud_data_Driver.csv")
raw_policy_data <- read_csv("Claim_Fraud_data_Policy.csv")
raw_vehicle_data <- read_csv("Claim_Fraud_data_Vehicle.csv")

## Creating a function to make the columns easier to work with
pretty_cols <- function(x) {
  x %>% 
    str_replace_all(pattern = " " ,replacement = "_") %>% 
    tolower()
}

## Changing the column names to make them easier to work with
colnames(raw_claims_data) <- colnames(raw_claims_data) %>% pretty_cols()
colnames(raw_assessment_data) <- colnames(raw_assessment_data) %>% pretty_cols()
colnames(raw_driver_data) <- colnames(raw_driver_data) %>% pretty_cols()
colnames(raw_policy_data) <- colnames(raw_policy_data) %>% pretty_cols()
colnames(raw_vehicle_data) <- colnames(raw_vehicle_data) %>% pretty_cols()

## Remove some extra columns at the end which should not be getting read in from the csv's
raw_assessment_data <- raw_assessment_data %>% 
  select(-contains("..."))

raw_driver_data <- raw_driver_data %>% 
  select(-contains("..."))

```

## Data Checking

```{r checking, echo=TRUE, include=FALSE}
#########################################################
## Data Checking & Joining
#########################################################
## Going to comment out sections that were previously used for checking
## Can uncomment those sections to see the checks

#### Policy Data Pre-Join Check
## Checking the uniqueness of the variables that we are going to be joining on
raw_policy_data %>%
  count(policy_id) %>%
  filter(n > 1) %>%
  arrange(desc(n))


```


```{r data_read2, include=FALSE}
## Policy Id is not unique ... 142 duplicates. Need to understand it better
# raw_policy_data %>%
#   filter(policy_id == "P101444063304") %>% View()

## Seems like it is a pure duplicate in this example
# raw_policy_data %>%
#   filter(policy_id == "P101444063304") %>%
#   unique()
```

```{r}
## Using unique fixes the issue
raw_policy_data %>%
  unique() %>%
  count(policy_id) %>%
  filter(n > 1) %>%
  arrange(desc(n))
```


```{r include=FALSE}
## Using unique fixes the issue
# raw_policy_data %>%
#   unique() %>%
#   count(policy_id) %>%
#   filter(n > 1) %>%
#   arrange(desc(n))

## Removing the duplicate records in the policy dataset
unique_policy_data <- raw_policy_data %>%
  unique()


#### Claims Data Pre-Join Check
## Checking the uniqueness of Claim Id
# raw_claims_data %>% 
#   count(claim_id) %>% 
#   filter(n > 1) %>% 
#   arrange(desc(n))

## Seeing if unique fixes the issue
# raw_claims_data %>%
#   unique() %>% 
#   count(claim_id) %>% 
#   arrange(desc(n))

## It does. Going to apply it to the raw_claims_data
unique_claims_data <- raw_claims_data %>%
  unique()


#### Driver Data Pre-Join Check
## Checking Driver Id
# raw_driver_data %>% 
#   count(driver_id) %>% 
#   filter(n > 1) %>% 
#   arrange(desc(n))

## Seeing if unique fixes the issue
# raw_driver_data %>%
#   unique() %>% 
#   count(driver_id) %>% 
#   filter(n > 1) %>% 
#   arrange(desc(n))

## It does. Going to apply it to the raw_driver_data
unique_driver_data <- raw_driver_data %>%
  unique() 


#### Vehicle Data Pre-Join Check
# raw_vehicle_data %>% 
#   count(vehicle_id) %>% 
#   filter(n > 1) %>% 
#   arrange(desc(n))

## Seeing if unique fixes the issue
# raw_vehicle_data %>%
#   unique() %>% 
#   count(vehicle_id) %>% 
#   filter(n > 1) %>% 
#   arrange(desc(n))

## It does. Going to apply it to the raw_vehicle_data
unique_vehicle_data <- raw_vehicle_data %>% 
  unique()

### Would normally remove most the code above as it's no longer necessary
### Could just keep the unique statements ... going to keep as-is 
### just to show the work behind finding the need for "unique"

## Combining all the datasets together
combined_data <- unique_claims_data %>% 
  left_join(unique_policy_data ,by = "policy_id") %>% 
  left_join(unique_driver_data ,by = "driver_id") %>% 
  left_join(unique_vehicle_data ,by = "vehicle_id") %>% 
  select(all_of(colnames(raw_assessment_data)) ,fraud_ind)
```



```{r include = FALSE}


#########################################################
## Claim Notes
#########################################################
## Digging into the claim notes to try to text mine/find predictive phrases
## Going to separate the notes by sentence
separated_claim_data <- combined_data %>% 
  select(claim_id ,claim_notes) %>% 
  separate_wider_delim(claim_notes 
                       ,delim = "." 
                       ,names_sep = "_"
                       ,too_few = "align_start"
  ) %>% 
  mutate_at(vars(contains("claim_notes")) ,str_trim) %>% 
  mutate_at(vars(contains("claim_notes")) ,function(x) {if_else(x == "" ,NA ,x)})

## Joining the notes back onto the original dataset
combined_data <- combined_data %>% 
  left_join(separated_claim_data ,by = "claim_id")

## Going to see how variables are correlated with fraud
check_fraud_pct <- function(x) {
  combined_data %>% 
    group_by(!!sym(x)) %>% 
    summarise(n          = n()
              ,fraud_ind = sum(fraud_ind)
              ,fraud_pct = fraud_ind / n) %>% 
    arrange(desc(n))
}

## A lot of the phrases/formats used actually do seem pretty consistent
# check_fraud_pct("claim_notes_1") %>% View()

## For claim_notes_1 can probably extract the intro phrase, vehicle (and make sure it matches)
## vehicle/object that was collided with, and then where it occurred

# check_fraud_pct("claim_notes_2") %>% View()

## For claim notes 2, this is useful to tell the severity of the injury
## Would likely be good to cross this with the incurred amount to see if they are inconsistent
## i.e. a small injury with a large loss amt

# check_fraud_pct("claim_notes_3") %>% View()

## For claim notes 3, this is useful as it has some thoughts around fraud
## Also has more info on injury severity and police report status

# check_fraud_pct("claim_notes_4") %>% View()


## Claim notes 4 has more information on the fraud, lots of blanks

# check_fraud_pct("claim_notes_5") %>% View()

## More fraud info in claim_notes_5

# check_fraud_pct("claim_notes_6") %>% View()

## All blanks for claim_notes_6 - can probably just be discarded

## Going to start with breaking down each of the claim notes
combined_data <- combined_data %>% 
  # select(claim_notes_1) %>% 
  mutate(note_type_1            = str_sub(claim_notes_1
                                          ,end = str_locate(claim_notes_1 ,pattern = ":")[,1])
         ,note_vehicle_1        = str_sub(claim_notes_1
                                          ,start = str_locate(claim_notes_1 ,pattern = "\\(")[,"start"]
                                          ,end = str_locate(claim_notes_1 ,pattern = "\\)")[,"start"]
         ) %>% 
           str_remove_all(pattern = "\\(|\\)") %>% 
           str_trim()
         ,fraud_ind_1           = str_extract(note_type_1 %>% 
                                                str_replace(pattern = "Frauuuuud" ,replacement = "Fraud") %>% 
                                                tolower()
                                              ,pattern = "fraud\\s*(\\S+)")
         ,pedestrian_flag_2     = str_extract(claim_notes_2 %>% tolower()
                                              ,pattern = "cyclist|pedestrian") %>% 
           coalesce("Other")
         ,injury_type_2         = str_extract(claim_notes_2 %>% tolower() 
                                              ,pattern = "(\\S+)\\s*damage|(\\S+)\\s*injuries")
         ,injury_level_2        = str_extract(claim_notes_2 %>% tolower() 
                                              ,pattern = "(\\S+)\\s*(?=damage)|(\\S+)\\s*(?=injuries)")
         ,injury_vs_damage_2    = str_extract(claim_notes_2 %>% tolower() 
                                              ,pattern = "damage|injuries")
         ,fraud_ind_2           = str_extract(claim_notes_2 %>% 
                                                tolower() %>% 
                                                str_replace(pattern = "frauuuuud" ,replacement = "fraud")
                                              ,pattern = "(\\S+)\\s*(\\S+)\\s*fraud")
         ,injury_type_3         = str_extract(claim_notes_3 %>% tolower() 
                                              ,pattern = "(\\S+)\\s*damage|(\\S+)\\s*injuries|injuries reported")
         ,injury_level_3        = str_extract(claim_notes_3 %>% tolower() 
                                              ,pattern = "(\\S+)\\s*(?=damage)|(\\S+)\\s*(?=injuries)")
         ,injury_vs_damage_3    = str_extract(claim_notes_3 %>% tolower() 
                                              ,pattern = "damage|injuries")         
         ,police_type_3         = str_extract(claim_notes_3 %>% tolower() 
                                              ,pattern = "police and medical assistance|police\\s*(\\S+)")
         ,triple_exclamation_3  = as.numeric(str_detect(claim_notes_3 ,pattern = "^!!!$"))
         ,fraud_ind_3           = str_extract(claim_notes_3 %>% 
                                                tolower() %>% 
                                                str_replace(pattern = "frauuuuud" ,replacement = "fraud")
                                              ,pattern = "(\\S+)\\s*(\\S+)\\s*fraud|fraud")
         ,police_type_4         = str_extract(claim_notes_4 %>% tolower() 
                                              ,pattern = "police and medical assistance|police\\s*(\\S+)|officer on site")
         ,alcohol_or_drugs_4    = str_extract(claim_notes_4 %>% tolower()
                                              ,pattern = "alcohol or drugs suspected")
         ,triple_exclamation_4  = as.numeric(str_detect(claim_notes_4 ,pattern = "^!!!$"))
         ,fraud_ind_4           = str_extract(claim_notes_4 %>% 
                                                tolower() %>% 
                                                str_replace(pattern = "frauuuuud" ,replacement = "fraud")
                                              ,pattern = "(\\S+)\\s*(\\S+)\\s*fraud|fraud|no signs of fraud")
         ,alcohol_or_drugs_5    = str_extract(claim_notes_5 %>% tolower()
                                              ,pattern = "alcohol or drugs suspected")
         ,triple_exclamation_5  = as.numeric(str_detect(claim_notes_5 ,pattern = "^!!!$"))
         ,fraud_ind_5           = str_extract(claim_notes_5 %>% 
                                                tolower() %>% 
                                                str_replace(pattern = "frauuuuud" ,replacement = "fraud")
                                              ,pattern = "(\\S+)\\s*(\\S+)\\s*fraud|fraud|no signs of fraud")
         ,note_type             = note_type_1 %>% 
                                     str_replace(pattern = "Frauuuuud|frauuuuud" ,replacement = "Fraud")
         ,vehicle_mismatch_flag = as.numeric(str_c(make ," " ,model) != note_vehicle_1)
         ,pedestrian_type       = pedestrian_flag_2
         ,injury_type           = if_else(!is.na(injury_type_2) & !is.na(injury_type_3)
                                          ,str_c(injury_type_2 ," and " ,injury_type_3)
                                          ,coalesce(injury_type_2 ,injury_type_3))
         ,police_type           = coalesce(police_type_3 ,police_type_4)
         ,alcohol_or_drugs      = coalesce(alcohol_or_drugs_4 ,alcohol_or_drugs_5)
         ,triple_exclamation    = as.numeric(coalesce(triple_exclamation_3 ,0) + coalesce(triple_exclamation_4 ,0) 
                                             + coalesce(triple_exclamation_5 ,0))
         ,fraud_note_ind        = if_else(!is.na(fraud_ind_1) & !is.na(fraud_ind_2) 
                                          ,str_c(fraud_ind_1 ," " ,fraud_ind_2)
                                          ,coalesce(fraud_ind_1 ,fraud_ind_2 ,fraud_ind_3 ,fraud_ind_4 ,fraud_ind_5
                                                    ,"no mention of fraud")
         )
         ,fraud_note_ind        = if_else(str_detect(fraud_note_ind ,pattern = "susp")
                                          ,"suspected fraud"
                                          ,fraud_note_ind
         ) %>% 
           factor(levels = c('no mention of fraud' ,'no signs of fraud' 
                             ,'probably not fraud' ,'suspected fraud' ,'fraud'))
  ) %>% 
  select(-matches("_[0-9]$"))

## Thought there would be instances where the claim notes vehicle doesn't match (which could indicate fraud)
## Turns out there aren't  --> remove column
combined_data <- combined_data %>% 
  select(-vehicle_mismatch_flag)
```



```{r}

## Going to see how variables are correlated with fraud
check_fraud_pct <- function(x) {
  combined_data %>% 
    group_by(!!sym(x)) %>% 
    summarise(n          = n()
              ,fraud_ind = sum(fraud_ind)
              ,fraud_pct = fraud_ind / n) %>% 
    arrange(desc(n))
}

check_fraud_pct("triple_exclamation") ## Extremely predictive ... although few data points
check_fraud_pct("fraud_note_ind") ## Extremely predictive ... although few data points

```



```{r include = FALSE}
#########################################################
## Exploratory Data Analysis - Numeric Columns
#########################################################
## Looking for missing values in the numeric fields
# combined_data %>% 
#   select_if(is.numeric) %>% 
#   summary()

## Roughly 23 - 38 NA's for most numeric fields
## No NA's for the Fraud Indicator

## Creating a function to look at the numeric variable bands and their fraud rates
check_fraud_pct_num <- function(x ,y = 5) {
  combined_data %>% 
    mutate(band = cut_number(!!sym(x) ,n = y ,dig.lab=10)) %>% 
    filter(!is.na(band)) %>% 
    group_by(band) %>% 
    summarise(n          = n()
              ,fraud_ind = sum(fraud_ind)
              ,fraud_pct = fraud_ind / n)
}  

## Creating a function to look at the numeric variables directly and their fraud rates
check_fraud_pct_num2 <- function(x) {
  combined_data %>% 
    filter(!is.na(!!sym(x))) %>% 
    group_by(!!sym(x)) %>% 
    summarise(n          = n()
              ,fraud_ind = sum(fraud_ind)
              ,fraud_pct = fraud_ind / n)
} 


```

```{r}
## Checking the numeric cols
check_fraud_pct_num2("num_drivers") ## less drivers seems more fraudulent ... fix those with 17
check_fraud_pct_num2("clms_flt1") ## Seems very predictive ... 1+ is very fraudulent ... fix those with 17
check_fraud_pct_num2("viol_mjr2") ## Seems very predictive ... 1+ is very fraudulent ... fix those with 17
```



```{r echo = TRUE ,results = 'hide'}
## Fixing the columns that were identified as having issues above
combined_data <- combined_data %>% 
  mutate(num_drivers_new      = na_if(num_drivers ,17)
         ,clms_flt1_new       = na_if(clms_flt1 ,17)
         ,late_90d_new        = na_if(late_90d ,500)
         ,outs_bal_new        = na_if(outs_bal ,99)
         ,viol_mjr2_new       = na_if(viol_mjr2 ,17)
         ,time_bet10pm2am_new = na_if(time_bet10pm2am ,0.75)
         ,credit_score_new    = na_if(credit_score ,1.5)
         ,report_lag_new      = na_if(report_lag ,99)
         ,pop_density         = na_if(pop_density ,5) %>% as.factor()
  )
```


```{r}
#########################################################
## Exploratory Data Analysis - Character Columns
#########################################################
## Checking their relationships to fraud
check_fraud_pct_num2("gender") ## Need to fix these fields
```



```{r echo = TRUE ,results = 'hide'}
## Fixing the inconsistent character fields
combined_data <- combined_data %>% 
  mutate(gender_new                = case_when(gender %in% c('Boy' ,'M' ,'Male') ~ 'Male'
                                               ,gender %in% c('F' ,'Female' ,'Girl') ~ 'Female') %>% 
                                                   factor(levels = c('Male' ,'Female'))
         ,education_new            = factor(education ,levels = c('Some High School' ,'High School or GED'
                                                                  ,'Bachelors' ,'Masters' ,'Doctorate'))
         ,limits_new               = str_replace_all(limits ,pattern = "k" ,replacement = "000") %>% 
                                        str_replace_all(pattern = "000$" ,replacement = "k") %>% 
                                        factor(levels = c("15k" ,"20k" ,"25k" ,"50k" ,"100k" ,"200k" ,"250k" ,"300k" ,"500k"))
         ,limits_numeric           = limits_new %>% 
                                        str_replace(pattern = "k" ,replacement = "000") %>% 
                                        as.numeric()
         ,marital_status_new       = case_when(marital_status %in% c('M' ,'Marr' ,'Married') ~ 'Married'
                                               ,marital_status %in% c('S' ,'Single') ~ 'Single') %>% 
           as.factor()
         ,num_cars_new             = case_when(num_cars == "Four" ~ "4"
                                               ,num_cars == "Three" ~ "3"
                                               ,num_cars == "Two" ~ "2"
                                               ,TRUE ~ num_cars
                                               ) %>% 
                                        as.factor()
         ,num_cars_band_new        = case_when(num_cars  == "1" ~ "1"
                                               ,num_cars == "2" ~ "2"
                                               ,num_cars == "3" ~ "3"
                                               ,num_cars == "4" ~ "4"
                                               ,TRUE ~ "5+") %>% 
                                        as.factor()         
         ,seat_belt_new            = seat_belt %>%
                                        factor(levels = c('Never' ,'Rarely' ,'Occasionally' ,'Usually' ,'Always' 
                                                          ,'Unknown'))
         ,income_new               = case_when(income %in% c('Mid' ,'Middle') ~ 'Middle'
                                               ,income %in% c('Working' ,'Wrk') ~ 'Working'
                                               ,TRUE ~ income) %>% 
                                        factor(levels = c('Poverty' ,'Working' ,'Middle' ,'Upper'))
         ,note_type_new            = case_when(!(note_type %in% c(":" ,"Fraud Suspected:" ,"Hit-and-run incident:")) ~ "All Other"
                                               ,TRUE ~ note_type) %>% 
                                        factor(levels = c(":" ,"All Other" ,"Hit-and-run incident:" ,"Fraud Suspected:"))
         ,pedestrian_type_new      = pedestrian_type %>% tolower() %>% factor(levels = c("other" ,"cyclist" ,"pedestrian"))
         ,injury_type_new          = injury_type %>% as.factor()
         ,police_type_new          = police_type %>% 
                                        coalesce("no mention of police") %>% 
                                        factor(levels = c("officer on site" ,"police report" 
                                                          ,"police and medical assistance"
                                                          ,"police notified" ,"no mention of police"))
         ,alcohol_or_drugs_new     = alcohol_or_drugs %>% coalesce("All Other") %>% as.factor()
         ,claim_greater_than_limit = as.numeric(claimamount > limits_numeric)
  ) 

## Confirming the new fields are looking better
# check_fraud_pct_num2("gender_new")
# check_fraud_pct_num2("education_new")
# check_fraud_pct_num2("limits_new")
# check_fraud_pct_num2("marital_status_new")
# check_fraud_pct_num2("num_cars_new")
# check_fraud_pct_num2("num_cars_band_new")
# check_fraud_pct_num2("seat_belt_new")
# check_fraud_pct_num2("income_new")
# check_fraud_pct_num2("pedestrian_type_new")
# check_fraud_pct_num2("injury_type_new")
# check_fraud_pct_num2("police_type_new")
# check_fraud_pct_num2("alcohol_or_drugs_new")
# check_fraud_pct_num2("claim_greater_than_limit")

## Fixing the columns that were identified as having issues above
combined_data <- combined_data %>% 
  mutate(num_cars_new = na_if(num_cars_new ,"17"))
```

```{r echo=TRUE ,results = 'hide'}
#########################################################
## Exploratory Data Analysis - Date Columns
#########################################################
## Converting to dates
combined_data <- combined_data %>% 
  mutate(policy_orig_eff_date_new = ymd(policy_orig_eff_date)
         ,accident_date_new       = ymd(accident_date)
         ,policy_month            = month(policy_orig_eff_date_new)
         ,policy_day              = day(policy_orig_eff_date_new)
         ,policy_day_of_week      = wday(policy_orig_eff_date_new ,label = TRUE)
         ,acc_month               = month(accident_date_new)
         ,acc_day                 = day(accident_date_new)
         ,acc_day_of_week         = wday(accident_date_new ,label = TRUE) 
         ,report_date             = accident_date_new + days(report_lag)
  )


## Date variables that are missing:
## 1) Report_date - re-created it with the report lag
```

```{r}
#########################################################
## Variable Relationships/Bucketing
#########################################################
## Creating a function to see the relationship b/w different variables
plot_x_y_vars <- function(x , y) {
  combined_data %>%
    filter(!!sym(x) != 0 & !!sym(y) != 0) %>% 
    mutate(indicator = if_else(!!sym(x) > !!sym(y)
                               ,"Weird"
                               ,"Normal") %>% 
             factor(levels = c("Weird" ,"Normal"))
    ) %>% 
    ggplot(aes(x = !!sym(x) ,fill = indicator)) +
    geom_bar() +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(str_c("~" ,y ,sep = " ")) +
    scale_y_continuous(label = comma) +
    ylab(y) 
}


## Looking at one of the variables that has x years
plot_x_y_vars("clms_flt1_new" ,"clms_flt2")
# plot_x_y_vars("clms_flt1_new" ,"clms_flt3")
# plot_x_y_vars("clms_flt1_new" ,"clms_flt4")
# plot_x_y_vars("clms_flt1_new" ,"clms_flt5")
# plot_x_y_vars("clms_flt2" ,"clms_flt3")
# plot_x_y_vars("clms_flt2" ,"clms_flt4")
# plot_x_y_vars("clms_flt2" ,"clms_flt5")
# plot_x_y_vars("clms_flt3" ,"clms_flt4")
# plot_x_y_vars("clms_flt3" ,"clms_flt5")
# plot_x_y_vars("clms_flt4" ,"clms_flt5")
```


